export const TIPE_UJIAN_LABELS: Record<string, string> = {
  TRYOUT: 'Try Out',
  LATIHAN: 'Latihan',
  QUIZ: 'Kuis',
};

export const STATUS_COLORS: Record<string, string> = {
  PENDING: 'bg-yellow-100 text-yellow-800',
  APPROVED: 'bg-green-100 text-green-800',
  REJECTED: 'bg-red-100 text-red-800',
  DITINJAU: 'bg-blue-100 text-blue-800',
  DIPERBAIKI: 'bg-green-100 text-green-800',
  DITOLAK: 'bg-red-100 text-red-800',
};

export const CATEGORY_CONFIG = {
  TWK: {
    fullLabel: "Tes Wawasan Kebangsaan",
    gradient: "from-violet-600 to-indigo-600",
    headerBg: "bg-gradient-to-r from-violet-600 to-indigo-600",
    lightBg: "bg-violet-50",
    border: "border-violet-200",
    badge: "bg-violet-100 text-violet-700",
    dot: "bg-violet-500",
    selectedBorder: "border-violet-500 bg-violet-50",
    selectedKey: "bg-violet-600 text-white",
    check: "text-violet-500",
    navActive: "bg-violet-600 text-white",
    navBg: "bg-violet-50",
    navText: "text-violet-700",
    navHeader: "bg-violet-600",
  },
  TIU: {
    fullLabel: "Tes Intelegensi Umum",
    gradient: "from-cyan-600 to-teal-600",
    headerBg: "bg-gradient-to-r from-cyan-600 to-teal-600",
    lightBg: "bg-cyan-50",
    border: "border-cyan-200",
    badge: "bg-cyan-100 text-cyan-700",
    dot: "bg-cyan-500",
    selectedBorder: "border-cyan-500 bg-cyan-50",
    selectedKey: "bg-cyan-600 text-white",
    check: "text-cyan-500",
    navActive: "bg-cyan-600 text-white",
    navBg: "bg-cyan-50",
    navText: "text-cyan-700",
    navHeader: "bg-cyan-600",
  },
  TKP: {
    fullLabel: "Tes Karakteristik Pribadi",
    gradient: "from-amber-500 to-orange-500",
    headerBg: "bg-gradient-to-r from-amber-500 to-orange-500",
    lightBg: "bg-amber-50",
    border: "border-amber-200",
    badge: "bg-amber-100 text-amber-700",
    dot: "bg-amber-500",
    selectedBorder: "border-amber-500 bg-amber-50",
    selectedKey: "bg-amber-500 text-white",
    check: "text-amber-500",
    navActive: "bg-amber-500 text-white",
    navBg: "bg-amber-50",
    navText: "text-amber-700",
    navHeader: "bg-amber-500",
  },
} as const;
